---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
spec:
  selector:
    environment: dev
    project: roboshop
    component: mongodb
    tier: db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: roboshop
spec:
  clusterIP: None   # REQUIRED for StatefulSet
  selector:
    environment: dev
    project: roboshop
    component: mongodb
    tier: db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: roboshop
spec:
  serviceName: "mongodb-headless"
  replicas: 1
  selector:
    matchLabels:
      environment: dev
      project: roboshop
      component: mongodb
      tier: db
  template:
    metadata:
      labels:
        environment: dev
        project: roboshop
        component: mongodb
        tier: db
    spec:
      containers:
      - name: mongodb
        image: anilkathoju/mongodb:v1
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb
          mountPath: /data/db

  volumeClaimTemplates:
  - metadata:
      name: mongodb
    spec:
      accessModes: 
        - ReadWriteOnce
      storageClassName: gp2     # EXISTING storage class in your cluster
      resources:
        requests:
          storage: 1Gi
