apiVersion: v1
kind: Service
metadata:
 name: mongodb
 namespace: roboshop
 labels:
    environment: dev
    project: roboshop
    tier: db
spec:
 selector:
   environment: dev
   project: roboshop
   tier: db
 ports:
  - protocol: TCP
    port: 27017  # servcie port
    targetPort: 27017 # container

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    environment: dev
    project: roboshop
    tier: db
spec:
 clusterIP: None
 selector: 
  labels:
    environment: dev
    project: roboshop
    tier: db
 ports:
  - protocol: TCP
    port: 27017  # servcie port
    targetPort: 27017 # container   
     

