apiVersion: v1
kind: Service
metadata:
 name: mongodb
 namespace: roboshop
 labels:
      environment: dev
      project: roboshop
spec:
selector:
    project: roboshop
    component: mongodb
    tier: db
    ports:
    - protocol: TCP
      port: 27017  # servcie port
      targetPort: 27017 # container

---

apiVersion: v1
kind: 
