---
apiVersion: v1
kind: Service
metadata:
 name: mongodb
 namespace: roboshop
spec:
 selector:
   environment: dev
   project: roboshop
   component: mongodb
   tier: db
 ports:
  - protocol: TCP
    port: 27017  # servcie port
    targetPort: 27017 # container

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: roboshop
spec:
  clusterIP: None
  selector: 
    eenvironment: dev
    project: roboshop
    component: mongodb
    tier: db
  ports:
    - protocol: TCP
      port: 27017  # servcie port
      targetPort: 27017 # container   

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: roboshop
spec:
  selector:
    matchLabels:
      environment: dev
      project: roboshop
      component: mongodb
      tier: db
  serviceName: "mongodb-headless"
  replicas: 1
  template:
    metadata:
      environment: dev
      project: roboshop
      component: mongodb
      tier: db
    spec:
      containers:
      - name: mongodb
        image: anilkathoju/mongodb:v1
        volumeMounts:
        - name: mongodb
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs"
      resources:
        requests:
          storage: 1Gi  





