---
apiVersion: v1
kind: Service
metadata:
   name: redis
   namespace: roboshop
spec:
  selector:
    environment: dev
    project: roboshop
    component: redis
    tier: db
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
   name: redis-headless
   namespace: roboshop
spec:
  clusterIP: None
  selector:
    environment: dev
    project: roboshop
    component: redis
    tier: db
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: redis
  namespace: roboshop
spec:
  selector:
    matchLabels:
      environment: dev
      project: roboshop
      component: redis
      tier: db
  serviceName: "redis-headless" # this should be head less service name
  replicas: 1
  template:
      metadata:
        labels:
          project: roboshop
          component: redis
          tier: db
      spec:
        containers:
        - name: redis
          image: redis:7.0
          volumeMounts:
          - name: redis
            mountPath: /data
    # This is PVC
      volumeClaimTemplates:
      - metadata:
        name: redis
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "roboshop-ebs"
        resources:
          requests:
            storage: 1Gi


